### ISSUE TITLE
Nice Theme! But No One Can Use It Without a License

### ISSUE THREAD

**Issue by ScriptGadget** [sharu725/karna#1]
From your listing on [jekyllthemes](http://jekyllthemes.org/themes/karna/) it seems you intended to include an MIT license? If you create a file named LICENSE.MD using the GitHub editor, it will present you with a list of templates you can use, or you can grab one from: [choosalicense.com](http://choosealicense.com/)

Great work. I really like the spacing and corner styling.

**Comment by sharu725** [comment]
Thanks @ScriptGadget. I have to do it for other themes as well.

**Comment by sharu725** [comment]
Licence added https://github.com/sharu725/karna/blob/gh-pages/LICENCE.md
