### ISSUE TITLE
How to host on my own machine?

### ISSUE THREAD

**Issue by zhangyouxin** [sharu725/karna#7]
I copied a Gemfile and Gemfile.lock , and ran `bundle exec jekyll serve` but it just does not work..

**Comment by sharu725** [comment]
Which Gemfile? what error message did you received?

**Comment by zhangyouxin** [comment]
I just cloned this repo and tried with `bundle exec jekyll serve` [jekyll](https://jekyllrb.com/) run the project, however it comes up with a error msg `Could not locate Gemfile or .bundle/ directory
` so I copied some Gemfile from another sample project provided by jekyll...
I just don't know how to run it on a local machine since I'm a junior in front-end....
so I'm looking for an answer
thank you so much

**Comment by sharu725** [comment]
Remove the Gemfile and Gemfile.lock and try running `jekyll serve`

**Comment by zhangyouxin** [comment]
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    Invalid US-ASCII character "\xE2" on line 74

**Comment by zhangyouxin** [comment]
weired。。。there is no line 74 at all

**Comment by sharu725** [comment]
This thread might help - `https://github.com/jekyll/jekyll/issues/4268`.
If you observe the last statement, it imports all the SCSS present in the `_sass` folder. So it has lines more than 100.

**Comment by zhangyouxin** [comment]
many thanks
