### ISSUE TITLE
How to have width parameter working? (What is "full version"?)

### ISSUE THREAD

**Issue by smoh** [sharu725/karna#8]
Hi, thanks for making this nice theme available. I'm having trouble using the `width` parameter to control post width. In the demo sites, it says this is only supported in the full version, but what is full  version?

**Comment by sharu725** [comment]
Yes, there are 3 widths available for posts. It is only available in the
full version which can be bought in About page.

**Comment by smoh** [comment]
Ah, I see. Thanks!
